name: loan_env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas
      - scikit-learn
      - mlflow
      - joblib
      - seaborn
      - matplotlib
